# .github/workflows/ci.yml

name: Node.js CI

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the correct version of Node.js
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # Cache npm dependencies for faster builds

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run your tests (if you have them)
      - name: Run tests
        run: npm test

      # Step 5: Run a linter to check for code style issues (good practice)
      - name: Run linter
        run: npx eslint 
